name: Build Webhook

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/webhook-build.yaml'
      - 'webhook/**/*.swift'
permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ./webhook
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"

      - run: swift package resolve $([ -f ./Package.resolved ] && echo "--force-resolved-versions" || true)

      - run: swift build -c release --static-swift-stdlib

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./webhook/.build/release/App"]'